#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

npm run check-format ||
(
    echo '❌ Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

npm run check-lint ||
(
        echo '❌ ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

npm run check-types ||
(
    echo '❌ Failed Type check.'
    false;
)

echo '✅✅✅✅ Commiting this now. ✅✅✅✅'